tuple = ("Stay","hungry",0,2)
print('Original tuple:\n',tuple)
print('tuple[0], tuple[3]:\n',tuple[0],tuple[3])
print('tuple[2:4]:\n',tuple[2:4])
print('tuple + (10, 20, "Stay", "foolish"):\n',tuple + (10, 20, "Stay", "foolish"))
print('tuple * 2:\n',tuple * 2)